name: Push containers to registries

on:
  pull_request:
    types: [closed]

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      matrix: ${{ steps.export-directories.outputs.matrix }} 
      any_changed: ${{ steps.changed-directories.outputs.any_changed }}
    if: github.event.pull_request.merged == true 

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Get SHA of last commit to main branch
        uses: nrwl/nx-set-shas@v3
        id: last_successful_commit_pull_request
        with:
          main-branch-name: ${{ steps.branch-name.outputs.base_ref_branch }} 

      - name: Get changed directories
        id: changed-directories
        uses: tj-actions/changed-files@v36
        with: 
          base_sha: ${{ steps.last_successful_commit_pull_request.outputs.base }}
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
          files: container/*/*.yml

      - name: Export changed directories
        id: export-directories
        run: echo "matrix={\"context\":${{ steps.changed-directories.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

  push_docker_containers:
    needs: setup
    if: needs.setup.outputs.any_changed == 'true'
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    permissions: 
      contents: read
      packages: write

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup up docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Get basename
        id: context_basename
        run: echo "basename=$(basename ${{ matrix.context }})" >> "$GITHUB_OUTPUT"

      - name: Log in to ghcr.io with docker
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{github.repository_owner}}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log in to quay.io with docker
        uses: docker/login-action@v2
        with:
          registry: quay.io
          username: ${{ vars.QUAYIO_USERNAME }}
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Log in to docker.io with docker
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ vars.DOCKERIO_USERNAME }}
          password: ${{ secrets.DOCKERIO_TOKEN }}

      - name: Build and push docker containers
        uses: docker/build-push-action@v4
        with:
          context: ${{ matrix.context }}
          file: .github/docker.df
          push: true
          tags: |
            ${{ steps.context_basename.outputs.basename }}_docker:latest
            ghcr.io/${{ steps.context_basename.outputs.basename }}_docker:latest
            quay.io/${{ steps.context_basename.outputs.basename }}_docker:latest
            docker.io/${{ steps.context_basename.outputs.basename }}_docker:latest

  push_apptainer_containers:
    needs: setup
    if: needs.setup.outputs.any_changed == 'true'
    if: github.event.pull_request.merged == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}
    permissions: 
      contents: read
      packages: write

      - name: Setup micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: containers
          create-args: apptainer
          generate-run-shell: true

      - name: Build apptainer containers
        shell: micromamba-shell {0}
        run: |
          pushd ${{ matrix.context}}; \
            apptainer build /tmp/${{ steps.context_basename.outputs.basename }}_apptainer.sif ${{ github.workspace }}/.github/apptainer.def; \
          popd

      - name: Log in to ghcr.io with apptainer
        shell: micromamba-shell {0}
        run: |
          apptainer remote login --username ${{ github.repository_owner }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            docker://ghcr.io/${{ github.repository_owner }}

      - name: Push apptainer containers to ghcr.io
        shell: micromamba-shell {0}
        run: |
          apptainer push \
            /tmp/${{ steps.context_basename.outputs.basename }}_apptainer.sif \
            oras://ghcr.io/${{ github.repository_owner }}/${{ steps.context_basename.outputs.basename }}_apptainer:latest'

      - name: Log in to quay.io with apptainer
        shell: micromamba-shell {0}
        run: |
          apptainer remote login --username ${{ vars.QUAYIO_USERNAME }} \
            --password ${{ secrets.QUAYIO_TOKEN }} \
            docker://quay.io/${{ vars.QUAYIO_USERNAME }}

      - name: Push apptainer containers to quay.io
        if: steps.download-apptainer-containers.outputs.found_artifact == 'true'
        shell: micromamba-shell {0}
        run: |
            apptainer push \
            /tmp/${{ steps.context_basename.outputs.basename }}_apptainer.sif \
            oras://quay.io/${{ vars.QUAYIO_USERNAME }}/${{ steps.context_basename.outputs.basename }}_apptainer:latest' 

      - name: Log in to docker.io with apptainer
        if: steps.download-apptainer-containers.outputs.found_artifact == 'true'
        shell: micromamba-shell {0}
        run: |
          apptainer remote login --username ${{ vars.DOCKERIO_USERNAME }} \
            --password ${{ secrets.DOCKERIO_TOKEN }} \
            docker://docker.io

      - name: Push apptainer containers to docker.io
        if: steps.download-apptainer-containers.outputs.found_artifact == 'true'
        shell: micromamba-shell {0}
        run: |
          apptainer push \
            /tmp/${{ steps.context_basename.outputs.basename }}_apptainer.sif \
            oras://docker.io/${{ vars.DOCKERIO_USERNAME }}/${{ steps.context_basename.outputs.basename }}_apptainer:latest'
